/**************************************************************
 * Copyright (c) 2008-2009 Daniel Pfeifer                     *
 *                                                            *
 * Distributed under the Boost Software License, Version 1.0. *
 **************************************************************/

#ifndef GLCC_PROC
# error GLCC_PROC must be defined before including this file!
#endif

// Version 1.0
GLCC_PROC(PFNGLCULLFACEPROC, glCullFace)
GLCC_PROC(PFNGLFRONTFACEPROC, glFrontFace)
GLCC_PROC(PFNGLHINTPROC, glHint)
GLCC_PROC(PFNGLLINEWIDTHPROC, glLineWidth)
GLCC_PROC(PFNGLPOINTSIZEPROC, glPointSize)
GLCC_PROC(PFNGLPOLYGONMODEPROC, glPolygonMode)
GLCC_PROC(PFNGLSCISSORPROC, glScissor)
GLCC_PROC(PFNGLTEXPARAMETERFPROC, glTexParameterf)
GLCC_PROC(PFNGLTEXPARAMETERFVPROC, glTexParameterfv)
GLCC_PROC(PFNGLTEXPARAMETERIPROC, glTexParameteri)
GLCC_PROC(PFNGLTEXPARAMETERIVPROC, glTexParameteriv)
GLCC_PROC(PFNGLTEXIMAGE1DPROC, glTexImage1D)
GLCC_PROC(PFNGLTEXIMAGE2DPROC, glTexImage2D)
GLCC_PROC(PFNGLDRAWBUFFERPROC, glDrawBuffer)
GLCC_PROC(PFNGLCLEARPROC, glClear)
GLCC_PROC(PFNGLCLEARCOLORPROC, glClearColor)
GLCC_PROC(PFNGLCLEARSTENCILPROC, glClearStencil)
GLCC_PROC(PFNGLCLEARDEPTHPROC, glClearDepth)
GLCC_PROC(PFNGLSTENCILMASKPROC, glStencilMask)
GLCC_PROC(PFNGLCOLORMASKPROC, glColorMask)
GLCC_PROC(PFNGLDEPTHMASKPROC, glDepthMask)
GLCC_PROC(PFNGLDISABLEPROC, glDisable)
GLCC_PROC(PFNGLENABLEPROC, glEnable)
GLCC_PROC(PFNGLFINISHPROC, glFinish)
GLCC_PROC(PFNGLFLUSHPROC, glFlush)
GLCC_PROC(PFNGLBLENDFUNCPROC, glBlendFunc)
GLCC_PROC(PFNGLLOGICOPPROC, glLogicOp)
GLCC_PROC(PFNGLSTENCILFUNCPROC, glStencilFunc)
GLCC_PROC(PFNGLSTENCILOPPROC, glStencilOp)
GLCC_PROC(PFNGLDEPTHFUNCPROC, glDepthFunc)
GLCC_PROC(PFNGLPIXELSTOREFPROC, glPixelStoref)
GLCC_PROC(PFNGLPIXELSTOREIPROC, glPixelStorei)
GLCC_PROC(PFNGLREADBUFFERPROC, glReadBuffer)
GLCC_PROC(PFNGLREADPIXELSPROC, glReadPixels)
GLCC_PROC(PFNGLGETBOOLEANVPROC, glGetBooleanv)
GLCC_PROC(PFNGLGETDOUBLEVPROC, glGetDoublev)
GLCC_PROC(PFNGLGETERRORPROC, glGetError)
GLCC_PROC(PFNGLGETFLOATVPROC, glGetFloatv)
GLCC_PROC(PFNGLGETINTEGERVPROC, glGetIntegerv)
GLCC_PROC(PFNGLGETSTRINGPROC, glGetString)
GLCC_PROC(PFNGLGETTEXIMAGEPROC, glGetTexImage)
GLCC_PROC(PFNGLGETTEXPARAMETERFVPROC, glGetTexParameterfv)
GLCC_PROC(PFNGLGETTEXPARAMETERIVPROC, glGetTexParameteriv)
GLCC_PROC(PFNGLGETTEXLEVELPARAMETERFVPROC, glGetTexLevelParameterfv)
GLCC_PROC(PFNGLGETTEXLEVELPARAMETERIVPROC, glGetTexLevelParameteriv)
GLCC_PROC(PFNGLISENABLEDPROC, glIsEnabled)
GLCC_PROC(PFNGLDEPTHRANGEPROC, glDepthRange)
GLCC_PROC(PFNGLVIEWPORTPROC, glViewport)

