/**************************************************************
 * Copyright (c) 2008-2009 Daniel Pfeifer                     *
 *                                                            *
 * Distributed under the Boost Software License, Version 1.0. *
 **************************************************************/

#ifndef GLCC_PROC
# error GLCC_PROC must be defined before including this file!
#endif

// Version 3.0
GLCC_PROC(PFNGLCOLORMASKIPROC, glColorMaski,)
GLCC_PROC(PFNGLGETBOOLEANI_VPROC, glGetBooleani_v,)
GLCC_PROC(PFNGLGETINTEGERI_VPROC, glGetIntegeri_v,)
GLCC_PROC(PFNGLENABLEIPROC, glEnablei,)
GLCC_PROC(PFNGLDISABLEIPROC, glDisablei,)
GLCC_PROC(PFNGLISENABLEDIPROC, glIsEnabledi,)
GLCC_PROC(PFNGLBEGINTRANSFORMFEEDBACKPROC, glBeginTransformFeedback,)
GLCC_PROC(PFNGLENDTRANSFORMFEEDBACKPROC, glEndTransformFeedback,)
GLCC_PROC(PFNGLBINDBUFFERRANGEPROC, glBindBufferRange,)
GLCC_PROC(PFNGLBINDBUFFERBASEPROC, glBindBufferBase,)
GLCC_PROC(PFNGLTRANSFORMFEEDBACKVARYINGSPROC, glTransformFeedbackVaryings,)
GLCC_PROC(PFNGLGETTRANSFORMFEEDBACKVARYINGPROC, glGetTransformFeedbackVarying,)
GLCC_PROC(PFNGLCLAMPCOLORPROC, glClampColor,)
GLCC_PROC(PFNGLBEGINCONDITIONALRENDERPROC, glBeginConditionalRender,)
GLCC_PROC(PFNGLENDCONDITIONALRENDERPROC, glEndConditionalRender,)
GLCC_PROC(PFNGLVERTEXATTRIBIPOINTERPROC, glVertexAttribIPointer,)
GLCC_PROC(PFNGLGETVERTEXATTRIBIIVPROC, glGetVertexAttribIiv,)
GLCC_PROC(PFNGLGETVERTEXATTRIBIUIVPROC, glGetVertexAttribIuiv,)
GLCC_PROC(PFNGLGETUNIFORMUIVPROC, glGetUniformuiv,)
GLCC_PROC(PFNGLBINDFRAGDATALOCATIONPROC, glBindFragDataLocation,)
GLCC_PROC(PFNGLGETFRAGDATALOCATIONPROC, glGetFragDataLocation,)
GLCC_PROC(PFNGLUNIFORM1UIPROC, glUniform1ui,)
GLCC_PROC(PFNGLUNIFORM2UIPROC, glUniform2ui,)
GLCC_PROC(PFNGLUNIFORM3UIPROC, glUniform3ui,)
GLCC_PROC(PFNGLUNIFORM4UIPROC, glUniform4ui,)
GLCC_PROC(PFNGLUNIFORM1UIVPROC, glUniform1uiv,)
GLCC_PROC(PFNGLUNIFORM2UIVPROC, glUniform2uiv,)
GLCC_PROC(PFNGLUNIFORM3UIVPROC, glUniform3uiv,)
GLCC_PROC(PFNGLUNIFORM4UIVPROC, glUniform4uiv,)
GLCC_PROC(PFNGLTEXPARAMETERIIVPROC, glTexParameterIiv,)
GLCC_PROC(PFNGLTEXPARAMETERIUIVPROC, glTexParameterIuiv,)
GLCC_PROC(PFNGLGETTEXPARAMETERIIVPROC, glGetTexParameterIiv,)
GLCC_PROC(PFNGLGETTEXPARAMETERIUIVPROC, glGetTexParameterIuiv,)
GLCC_PROC(PFNGLCLEARBUFFERIVPROC, glClearBufferiv,)
GLCC_PROC(PFNGLCLEARBUFFERUIVPROC, glClearBufferuiv,)
GLCC_PROC(PFNGLCLEARBUFFERFVPROC, glClearBufferfv,)
GLCC_PROC(PFNGLCLEARBUFFERFIPROC, glClearBufferfi,)
GLCC_PROC(PFNGLGETSTRINGIPROC, glGetStringi,)
