/**************************************************************
 * Copyright (c) 2008-2009 Daniel Pfeifer                     *
 *                                                            *
 * Distributed under the Boost Software License, Version 1.0. *
 **************************************************************/

#ifndef GLCC_PROC
# error GLCC_PROC must be defined before including this file!
#endif

// Version 1.3
GLCC_PROC(PFNGLXGETFBCONFIGSPROC, glXGetFBConfigs)
GLCC_PROC(PFNGLXCHOOSEFBCONFIGPROC, glXChooseFBConfig)
GLCC_PROC(PFNGLXGETFBCONFIGATTRIBPROC, glXGetFBConfigAttrib)
GLCC_PROC(PFNGLXGETVISUALFROMFBCONFIGPROC, glXGetVisualFromFBConfig)
GLCC_PROC(PFNGLXCREATEWINDOWPROC, glXCreateWindow)
GLCC_PROC(PFNGLXDESTROYWINDOWPROC, glXDestroyWindow)
GLCC_PROC(PFNGLXCREATEPIXMAPPROC, glXCreatePixmap)
GLCC_PROC(PFNGLXDESTROYPIXMAPPROC, glXDestroyPixmap)
GLCC_PROC(PFNGLXCREATEPBUFFERPROC, glXCreatePbuffer)
GLCC_PROC(PFNGLXDESTROYPBUFFERPROC, glXDestroyPbuffer)
GLCC_PROC(PFNGLXQUERYDRAWABLEPROC, glXQueryDrawable)
GLCC_PROC(PFNGLXCREATENEWCONTEXTPROC, glXCreateNewContext)
GLCC_PROC(PFNGLXMAKECONTEXTCURRENTPROC, glXMakeContextCurrent)
GLCC_PROC(PFNGLXGETCURRENTREADDRAWABLEPROC, glXGetCurrentReadDrawable)
GLCC_PROC(PFNGLXGETCURRENTDISPLAYPROC, glXGetCurrentDisplay)
GLCC_PROC(PFNGLXQUERYCONTEXTPROC, glXQueryContext)
GLCC_PROC(PFNGLXSELECTEVENTPROC, glXSelectEvent)
GLCC_PROC(PFNGLXGETSELECTEDEVENTPROC, glXGetSelectedEvent)

// Version 1.4
GLCC_PROC(PFNGLXGETPROCADDRESSPROC, glXGetProcAddress)

// GLX_ARB_get_proc_address
GLCC_PROC(PFNGLXGETPROCADDRESSARBPROC, glXGetProcAddressARB)

// GLX_ARB_create_context
GLCC_PROC(PFNGLXCREATECONTEXTATTRIBSARBPROC, glXCreateContextAttribsARB)

// GLX_SGI_swap_control
GLCC_PROC(PFNGLXSWAPINTERVALSGIPROC, glXSwapIntervalSGI)

// GLX_SGI_video_sync
GLCC_PROC(PFNGLXGETVIDEOSYNCSGIPROC, glXGetVideoSyncSGI)
GLCC_PROC(PFNGLXWAITVIDEOSYNCSGIPROC, glXWaitVideoSyncSGI)

// GLX_SGI_make_current_read
GLCC_PROC(PFNGLXMAKECURRENTREADSGIPROC, glXMakeCurrentReadSGI)
GLCC_PROC(PFNGLXGETCURRENTREADDRAWABLESGIPROC, glXGetCurrentReadDrawableSGI)

// GLX_SGIX_video_source
#ifdef _VL_H
GLCC_PROC(PFNGLXCREATEGLXVIDEOSOURCESGIXPROC, glXCreateGLXVideoSourceSGIX)
GLCC_PROC(PFNGLXDESTROYGLXVIDEOSOURCESGIXPROC, glXDestroyGLXVideoSourceSGIX)
#endif /* _VL_H */

// GLX_EXT_import_context
GLCC_PROC(PFNGLXGETCURRENTDISPLAYEXTPROC, glXGetCurrentDisplayEXT)
GLCC_PROC(PFNGLXQUERYCONTEXTINFOEXTPROC, glXQueryContextInfoEXT)
GLCC_PROC(PFNGLXGETCONTEXTIDEXTPROC, glXGetContextIDEXT)
GLCC_PROC(PFNGLXIMPORTCONTEXTEXTPROC, glXImportContextEXT)
GLCC_PROC(PFNGLXFREECONTEXTEXTPROC, glXFreeContextEXT)

// GLX_SGIX_fbconfig
GLCC_PROC(PFNGLXGETFBCONFIGATTRIBSGIXPROC, glXGetFBConfigAttribSGIX)
GLCC_PROC(PFNGLXCHOOSEFBCONFIGSGIXPROC, glXChooseFBConfigSGIX)
GLCC_PROC(PFNGLXCREATEGLXPIXMAPWITHCONFIGSGIXPROC, glXCreateGLXPixmapWithConfigSGIX)
GLCC_PROC(PFNGLXCREATECONTEXTWITHCONFIGSGIXPROC, glXCreateContextWithConfigSGIX)
GLCC_PROC(PFNGLXGETVISUALFROMFBCONFIGSGIXPROC, glXGetVisualFromFBConfigSGIX)
GLCC_PROC(PFNGLXGETFBCONFIGFROMVISUALSGIXPROC, glXGetFBConfigFromVisualSGIX)

// GLX_SGIX_pbuffer
GLCC_PROC(PFNGLXCREATEGLXPBUFFERSGIXPROC, glXCreateGLXPbufferSGIX)
GLCC_PROC(PFNGLXDESTROYGLXPBUFFERSGIXPROC, glXDestroyGLXPbufferSGIX)
GLCC_PROC(PFNGLXQUERYGLXPBUFFERSGIXPROC, glXQueryGLXPbufferSGIX)
GLCC_PROC(PFNGLXSELECTEVENTSGIXPROC, glXSelectEventSGIX)
GLCC_PROC(PFNGLXGETSELECTEDEVENTSGIXPROC, glXGetSelectedEventSGIX)

// GLX_SGI_cushion
GLCC_PROC(PFNGLXCUSHIONSGIPROC, glXCushionSGI)

// GLX_SGIX_video_resize
GLCC_PROC(PFNGLXBINDCHANNELTOWINDOWSGIXPROC, glXBindChannelToWindowSGIX)
GLCC_PROC(PFNGLXCHANNELRECTSGIXPROC, glXChannelRectSGIX)
GLCC_PROC(PFNGLXQUERYCHANNELRECTSGIXPROC, glXQueryChannelRectSGIX)
GLCC_PROC(PFNGLXQUERYCHANNELDELTASSGIXPROC, glXQueryChannelDeltasSGIX)
GLCC_PROC(PFNGLXCHANNELRECTSYNCSGIXPROC, glXChannelRectSyncSGIX)

// GLX_SGIX_dmbuffer
#ifdef _DM_BUFFER_H_
GLCC_PROC(PFNGLXASSOCIATEDMPBUFFERSGIXPROC, glXAssociateDMPbufferSGIX)
#endif /* _DM_BUFFER_H_ */

// GLX_SGIX_swap_group
GLCC_PROC(PFNGLXJOINSWAPGROUPSGIXPROC, glXJoinSwapGroupSGIX)

// GLX_SGIX_swap_barrier
GLCC_PROC(PFNGLXBINDSWAPBARRIERSGIXPROC, glXBindSwapBarrierSGIX)
GLCC_PROC(PFNGLXQUERYMAXSWAPBARRIERSSGIXPROC, glXQueryMaxSwapBarriersSGIX)

// GLX_SUN_get_transparent_index
GLCC_PROC(PFNGLXGETTRANSPARENTINDEXSUNPROC, glXGetTransparentIndexSUN)

// GLX_MESA_copy_sub_buffer
GLCC_PROC(PFNGLXCOPYSUBBUFFERMESAPROC, glXCopySubBufferMESA)

// GLX_MESA_pixmap_colormap
GLCC_PROC(PFNGLXCREATEGLXPIXMAPMESAPROC, glXCreateGLXPixmapMESA)

// GLX_MESA_release_buffers
GLCC_PROC(PFNGLXRELEASEBUFFERSMESAPROC, glXReleaseBuffersMESA)

// GLX_MESA_set_3dfx_mode
GLCC_PROC(PFNGLXSET3DFXMODEMESAPROC, glXSet3DfxModeMESA)

// GLX_OML_sync_control
GLCC_PROC(PFNGLXGETSYNCVALUESOMLPROC, glXGetSyncValuesOML)
GLCC_PROC(PFNGLXGETMSCRATEOMLPROC, glXGetMscRateOML)
GLCC_PROC(PFNGLXSWAPBUFFERSMSCOMLPROC, glXSwapBuffersMscOML)
GLCC_PROC(PFNGLXWAITFORMSCOMLPROC, glXWaitForMscOML)
GLCC_PROC(PFNGLXWAITFORSBCOMLPROC, glXWaitForSbcOML)

// GLX_SGIX_hyperpipe
GLCC_PROC(PFNGLXQUERYHYPERPIPENETWORKSGIXPROC, glXQueryHyperpipeNetworkSGIX)
GLCC_PROC(PFNGLXHYPERPIPECONFIGSGIXPROC, glXHyperpipeConfigSGIX)
GLCC_PROC(PFNGLXQUERYHYPERPIPECONFIGSGIXPROC, glXQueryHyperpipeConfigSGIX)
GLCC_PROC(PFNGLXDESTROYHYPERPIPECONFIGSGIXPROC, glXDestroyHyperpipeConfigSGIX)
GLCC_PROC(PFNGLXBINDHYPERPIPESGIXPROC, glXBindHyperpipeSGIX)
GLCC_PROC(PFNGLXQUERYHYPERPIPEBESTATTRIBSGIXPROC, glXQueryHyperpipeBestAttribSGIX)
GLCC_PROC(PFNGLXHYPERPIPEATTRIBSGIXPROC, glXHyperpipeAttribSGIX)
GLCC_PROC(PFNGLXQUERYHYPERPIPEATTRIBSGIXPROC, glXQueryHyperpipeAttribSGIX)

// GLX_MESA_agp_offset
GLCC_PROC(PFNGLXGETAGPOFFSETMESAPROC, glXGetAGPOffsetMESA)

// GLX_EXT_texture_from_pixmap
GLCC_PROC(PFNGLXBINDTEXIMAGEEXTPROC, glXBindTexImageEXT)
GLCC_PROC(PFNGLXRELEASETEXIMAGEEXTPROC, glXReleaseTexImageEXT)
