//Copyright (c) 2009 Emil Dotchevski and Reverge Studios, Inc.

//Distributed under the Boost Software License, Version 1.0. (See accompanying
//file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_LA_CUSTOM_MATRIX_MUL_VECTOR_HPP_INCLUDED
#define BOOST_LA_CUSTOM_MATRIX_MUL_VECTOR_HPP_INCLUDED

//This file was generated by a program. Do not edit manually.

#include <boost/la/config.hpp>
#include <boost/la/custom/matrix_mul_vector_2_2.hpp>
#include <boost/la/custom/matrix_mul_vector_3_3.hpp>
#include <boost/la/custom/matrix_mul_vector_4_4.hpp>

#endif
