//Copyright (c) 2009 Emil Dotchevski and Reverge Studios, Inc.

//Distributed under the Boost Software License, Version 1.0. (See accompanying
//file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_LA_CUSTOM_MATRIX_MAKE_HPP_INCLUDED
#define BOOST_LA_CUSTOM_MATRIX_MAKE_HPP_INCLUDED

//This file was generated by a program. Do not edit manually.

#include <boost/la/config.hpp>
#include <boost/la/custom/matrix_make_2_2.hpp>
#include <boost/la/custom/matrix_make_2_1.hpp>
#include <boost/la/custom/matrix_make_1_2.hpp>
#include <boost/la/custom/matrix_make_3_3.hpp>
#include <boost/la/custom/matrix_make_3_1.hpp>
#include <boost/la/custom/matrix_make_1_3.hpp>
#include <boost/la/custom/matrix_make_4_4.hpp>
#include <boost/la/custom/matrix_make_4_1.hpp>
#include <boost/la/custom/matrix_make_1_4.hpp>

#endif
