//Copyright (c) 2009 Emil Dotchevski and Reverge Studios, Inc.

//Distributed under the Boost Software License, Version 1.0. (See accompanying
//file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_LA_CUSTOM_MATRIX_MUL_MATRIX_1_4_4_HPP_INCLUDED
#define BOOST_LA_CUSTOM_MATRIX_MUL_MATRIX_1_4_4_HPP_INCLUDED

//This file was generated by a program. Do not edit manually.

#include <boost/la/config.hpp>
#include <boost/la/deduce_matrix.hpp>
#include <boost/utility/enable_if.hpp>
#include <boost/static_assert.hpp>

namespace
boost
    {
    namespace
    la
        {
        template <class A,class B>
        BOOST_LA_INLINE_OPERATIONS
        typename lazy_enable_if_c<
            matrix_traits<A>::rows==1 && matrix_traits<B>::rows==4 &&
            matrix_traits<A>::cols==4 && matrix_traits<B>::cols==4,
            deduce_matrix2<A,B,1,4> >::type
        operator*( A const & a, B const & b )
            {
            typedef typename matrix_traits<A>::scalar_type Ta;
            typedef typename matrix_traits<B>::scalar_type Tb;
            Ta const a00 = matrix_traits<A>::template r<0,0>(a);
            Ta const a01 = matrix_traits<A>::template r<0,1>(a);
            Ta const a02 = matrix_traits<A>::template r<0,2>(a);
            Ta const a03 = matrix_traits<A>::template r<0,3>(a);
            Tb const b00 = matrix_traits<B>::template r<0,0>(b);
            Tb const b01 = matrix_traits<B>::template r<0,1>(b);
            Tb const b02 = matrix_traits<B>::template r<0,2>(b);
            Tb const b03 = matrix_traits<B>::template r<0,3>(b);
            Tb const b10 = matrix_traits<B>::template r<1,0>(b);
            Tb const b11 = matrix_traits<B>::template r<1,1>(b);
            Tb const b12 = matrix_traits<B>::template r<1,2>(b);
            Tb const b13 = matrix_traits<B>::template r<1,3>(b);
            Tb const b20 = matrix_traits<B>::template r<2,0>(b);
            Tb const b21 = matrix_traits<B>::template r<2,1>(b);
            Tb const b22 = matrix_traits<B>::template r<2,2>(b);
            Tb const b23 = matrix_traits<B>::template r<2,3>(b);
            Tb const b30 = matrix_traits<B>::template r<3,0>(b);
            Tb const b31 = matrix_traits<B>::template r<3,1>(b);
            Tb const b32 = matrix_traits<B>::template r<3,2>(b);
            Tb const b33 = matrix_traits<B>::template r<3,3>(b);
            typedef typename deduce_matrix2<A,B,1,4>::type R;
            BOOST_STATIC_ASSERT(matrix_traits<R>::rows==1);
            BOOST_STATIC_ASSERT(matrix_traits<R>::cols==4);
            R r;
            matrix_traits<R>::template w<0,0>(r)=a00*b00+a01*b10+a02*b20+a03*b30;
            matrix_traits<R>::template w<0,1>(r)=a00*b01+a01*b11+a02*b21+a03*b31;
            matrix_traits<R>::template w<0,2>(r)=a00*b02+a01*b12+a02*b22+a03*b32;
            matrix_traits<R>::template w<0,3>(r)=a00*b03+a01*b13+a02*b23+a03*b33;
            return r;
            }

        namespace
        la_detail
            {
            template <int M,int N,int P>
            struct matrix_mul_matrix_defined;

            template <>
            struct
            matrix_mul_matrix_defined<1,4,4>
                {
                static bool const value=true;
                };
            }
        }
    }

#endif
