//Copyright (c) 2009 Emil Dotchevski and Reverge Studios, Inc.

//Distributed under the Boost Software License, Version 1.0. (See accompanying
//file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_LA_CUSTOM_SWIZZLE_3_HPP_INCLUDED
#define BOOST_LA_CUSTOM_SWIZZLE_3_HPP_INCLUDED

//This file was generated by a program. Do not edit manually.

#include <boost/la/config.hpp>
#include <boost/la/detail/swizzle_traits.hpp>

namespace
boost
    {
    namespace
    la
        {
        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        WW1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        ZW1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        YW1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        XW1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        WZ1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        ZZ1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        YZ1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        XZ1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        WY1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        ZY1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        YY1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        XY1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        WX1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        ZX1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        YX1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >
        XX1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        WW0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        ZW0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        YW0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        XW0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        WZ0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        ZZ0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        YZ0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        XZ0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        WY0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        ZY0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        YY0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        XY0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        WX0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        ZX0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        YX0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >
        XX0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        WWW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        ZWW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        YWW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        XWW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        WZW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        ZZW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        YZW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        XZW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        WYW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        ZYW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        YYW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        XYW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        WXW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        ZXW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        YXW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >
        XXW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        WWZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        ZWZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        YWZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        XWZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        WZZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        ZZZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        YZZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        XZZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        WYZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        ZYZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        YYZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        XYZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        WXZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        ZXZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        YXZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >
        XXZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        WWY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        ZWY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        YWY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        XWY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        WZY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        ZZY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        YZY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        XZY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        WYY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        ZYY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        YYY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        XYY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        WXY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        ZXY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        YXY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >
        XXY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        WWX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        ZWX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        YWX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        XWX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        WZX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        ZZX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        YZX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        XZX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        WYX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        ZYX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        YYX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        XYX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        WXX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        ZXX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        YXX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >
        XXX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > > >(); }
        }
    }

#endif
