//Copyright (c) 2009 Emil Dotchevski and Reverge Studios, Inc.

//Distributed under the Boost Software License, Version 1.0. (See accompanying
//file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_LA_CUSTOM_SWIZZLE_2_HPP_INCLUDED
#define BOOST_LA_CUSTOM_SWIZZLE_2_HPP_INCLUDED

//This file was generated by a program. Do not edit manually.

#include <boost/la/config.hpp>
#include <boost/la/detail/swizzle_traits.hpp>

namespace
boost
    {
    namespace
    la
        {
        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >
        W1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >
        Z1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >
        Y1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >
        X1() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_1_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >
        W0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >
        Z0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >
        Y0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >
        X0() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_0_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >
        WW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >
        ZW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >
        YW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >
        XW() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >
        WZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >
        ZZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >
        YZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >
        XZ() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >
        WY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >
        ZY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >
        YY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >
        XY() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >
        WX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_w_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >
        ZX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_z_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >
        YX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_y_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >(); }

        BOOST_LA_INLINE_TRIVIAL
        la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >
        XX() { return la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value,la_detail::swizzle_idx<la_detail::swizzle_tag<_x_>::value > >(); }
        }
    }

#endif
